//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class quiz_summary
    {
        public int id { get; set; }
        public int quiz_id { get; set; }
        public int user_id { get; set; }
        public int current_question_id { get; set; }
    
        public virtual question question { get; set; }
        public virtual quiz quiz { get; set; }
        public virtual user user { get; set; }
    }
}
