//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quiz_webappEntities : DbContext
    {
        public quiz_webappEntities()
            : base("name=quiz_webappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<option> options { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<question_type> question_type { get; set; }
        public virtual DbSet<quiz> quizs { get; set; }
        public virtual DbSet<quiz_users> quiz_users { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<team_users> team_users { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
